// propertiesData.js
export const propertiesData = [
  {
    id: 1,
    avenue: "Av. España",
    cityCountry: "Trujillo, Perú",
    price: "S/ 350,000",
    numericPrice: 350000,
    rooms: 4,
    bathrooms: 2,
    levels: 2,
    mt2: 1234,
    type: "COMPRA",
    imageUrl:
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/18/55/99/1d/casa.jpg?w=1200&h=-1&s=1",
    isFavorite: false,
  },
  {
    id: 2,
    avenue: "Av. Fátima",
    cityCountry: "Trujillo, Perú",
    price: "S/ 420,000",
    numericPrice: 420000,
    rooms: 5,
    bathrooms: 3,
    levels: 2,
    mt2: 1500,
    type: "COMPRA",
    imageUrl:
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/18/55/99/1d/casa.jpg?w=1200&h=-1&s=1",
    isFavorite: true,
  },
  {
    id: 3,
    avenue: "Av. América",
    cityCountry: "Trujillo, Perú",
    price: "S/ 2,500/mes",
    numericPrice: 2500,
    rooms: 3,
    bathrooms: 2,
    levels: 1,
    mt2: 120,
    type: "ALQUILER",
    imageUrl:
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/18/55/99/1d/casa.jpg?w=1200&h=-1&s=1",
    isFavorite: false,
  },
  {
    id: 4,
    avenue: "Av. Larco",
    cityCountry: "Trujillo, Perú",
    price: "S/ 180,000",
    numericPrice: 180000,
    rooms: 2,
    bathrooms: 1,
    levels: 1,
    mt2: 85,
    type: "COMPRA",
    imageUrl:
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/18/55/99/1d/casa.jpg?w=1200&h=-1&s=1",
    isFavorite: false,
  },
  {
    id: 5,
    avenue: "Av. Húsares",
    cityCountry: "Trujillo, Perú",
    price: "S/ 550,000",
    numericPrice: 550000,
    rooms: 5,
    bathrooms: 4,
    levels: 3,
    mt2: 2100,
    type: "COMPRA",
    imageUrl:
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/18/55/99/1d/casa.jpg?w=1200&h=-1&s=1",
    isFavorite: true,
  },
  {
    id: 6,
    avenue: "Av. Metropolitana",
    cityCountry: "Trujillo, Perú",
    price: "S/ 1,800/mes",
    numericPrice: 1800,
    rooms: 3,
    bathrooms: 2,
    levels: 1,
    mt2: 95,
    type: "ALQUILER",
    imageUrl:
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/18/55/99/1d/casa.jpg?w=1200&h=-1&s=1",
    isFavorite: false,
  },
];
